import IcnArrowLeftRetroSvg from './icn-arrow-left-retro-computer.svg';
import IcnArrowRightRetroSvg from './icn-arrow-right-retro-computer.svg';
import IcnArrowUpSvg from './icn-arrow-up.svg';
import IcnArrowUpRetroSvg from './icn-arrow-up-retro-computer.svg';
import IcnCaretDownSvg from './icn-caret-down.svg';
import IcnCaretUpSvg from './icn-caret-up.svg';
import IcnChatSvg from './icn-chat.svg';
import IcnChevronDownSvg from './icn-chevron-down.svg';
import IcnCircleInfoSvg from './icn-circle-info.svg';
import IcnDiscordSvg from './icn-discord.svg';
import IcnFileSvg from './icn-file.svg';
import IcnGithubSvg from './icn-github.svg';
import IcnLavaChartSvg from './icn-lava-chart.svg';
import IcnLavaCodeSvg from './icn-lava-code.svg';
import IcnLavaCubeSvg from './icn-lava-cube.svg';
import IcnLavaDocsSvg from './icn-lava-docs.svg';
import IcnLavaGitSvg from './icn-lava-git.svg';
import IcnLongArrowLeftSvg from './icn-long-arrow-left.svg';
import IcnLongArrowRightSvg from './icn-long-arrow-right.svg';
import IcnSearchSvg from './icn-search.svg';
import IcnShowSvg from './icn-show.svg';
import IcnTeamSvg from './icn-team.svg';
import IcnTelegramSvg from './icn-telegram.svg';
import IcnXSvg from './icn-x.svg';

export const IcnArrowLeftRetro = IcnArrowLeftRetroSvg;
export const IcnArrowRightRetro = IcnArrowRightRetroSvg;
export const IcnArrowUp = IcnArrowUpSvg;
export const IcnArrowUpRetro = IcnArrowUpRetroSvg;
export const IcnCaretDown = IcnCaretDownSvg;
export const IcnCaretUp = IcnCaretUpSvg;
export const IcnChat = IcnChatSvg;
export const IcnChevronDown = IcnChevronDownSvg;
export const IcnCircleInfo = IcnCircleInfoSvg;
export const IcnDiscord = IcnDiscordSvg;
export const IcnFile = IcnFileSvg;
export const IcnGithub = IcnGithubSvg;
export const IcnLavaChart = IcnLavaChartSvg;
export const IcnLavaCode = IcnLavaCodeSvg;
export const IcnLavaCube = IcnLavaCubeSvg;
export const IcnLavaDocs = IcnLavaDocsSvg;
export const IcnLavaGit = IcnLavaGitSvg;
export const IcnLongArrowLeft = IcnLongArrowLeftSvg;
export const IcnLongArrowRight = IcnLongArrowRightSvg;
export const IcnSearch = IcnSearchSvg;
export const IcnShow = IcnShowSvg;
export const IcnTeam = IcnTeamSvg;
export const IcnTelegram = IcnTelegramSvg;
export const IcnX = IcnXSvg;
