import { IChain, IPool } from '@/types';
import { IcnAxelar, IcnCelestia, IcnEvmos, IcnNear, IcnStarknet } from '@assets/images/rounded-chains';

export const initialChains = [
  {
    name: 'Agoric',
    requests: 105,
    rpcProviders: 6,
    service: 'RPC',
  },
  {
    name: 'Aptos',
    requests: 976,
    rpcProviders: 13,
    service: 'Indexers',
  },
  {
    name: 'Arbitrum',
    requests: 847,
    rpcProviders: 3,
    service: 'RPC',
  },
  {
    name: 'Avalanche',
    requests: 344,
    rpcProviders: 5,
    service: 'RPC',
  },
  {
    name: 'Base',
    requests: 437,
    rpcProviders: 14,
    service: 'RPC',
  },
  {
    name: 'Beacon',
    requests: 234,
    rpcProviders: 3,
    service: 'RPC',
  },
  {
    name: 'Berachain',
    requests: 164,
    rpcProviders: 9,
    service: 'RPC',
  },
  {
    name: 'Canto',
    requests: 543,
    rpcProviders: 5,
    service: 'RPC',
  },
];

export const homeSectionPools: IPool[] = [
  {
    id: 'near',
    title: 'Near',
    service: 'RPC',
    node_runner: 12,
    requests: 1.6,
    value: '$100,239.53',
    currency: 'NEAR',
    monthly_rewards: 27434.23,
    future_rewards: 220728.83,
    past_rewards: 109348.93,
    icon: <IcnNear/>,
    rpc_url: 'http://docs.lavanet.xyz/provider-setup',
  },
  {
    id: 'evmos',
    title: 'Evmos',
    service: 'Indexers',
    node_runner: 12,
    requests: 1.6,
    value: '$56,782.29',
    currency: 'EVMOS',
    monthly_rewards: 143923.8,
    future_rewards: 100293.2,
    past_rewards: 41726.0,
    icon: <IcnEvmos/>,
    rpc_url: 'http://docs.lavanet.xyz/provider-setup',
  },
  {
    id: "axelar",
    title: 'Axelar',
    service: 'RPC',
    node_runner: 12,
    requests: 1.6,
    value: '$24,882.63',
    currency: 'AXL',
    monthly_rewards: 39238.58,
    future_rewards: 110342.89,
    past_rewards: 85673.38,
    icon: <IcnAxelar/>,
    rpc_url: 'http://docs.lavanet.xyz/provider-setup',
  },
  {
    id: 'starknet',
    title: 'Starknet',
    service: 'RPC',
    node_runner: 12,
    requests: 1.6,
    value: '$100,239.53',
    currency: 'STRK',
    monthly_rewards: 27434.23,
    future_rewards: 220728.83,
    past_rewards: 109348.93,
    icon: <IcnStarknet/>,
    rpc_url: 'http://docs.lavanet.xyz/provider-setup',
  },
  {
    id: 'celestia',
    title: 'Celestia',
    service: 'RPC',
    node_runner: 12,
    requests: 1.6,
    value: '$24,882.63',
    currency: 'LAVA',
    monthly_rewards: 27434.23,
    future_rewards: 220728.83,
    past_rewards: 109348.93,
    icon: <IcnCelestia/>,
    rpc_url: 'http://docs.lavanet.xyz/provider-setup',
  },
];
